In [3]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [5]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [6]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [7]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [8]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [9]:
from sklearn.ensemble import RandomForestRegressor

In [10]:
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],'max_features': ['auto','sqrt','log2'],'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
#fitting the model for grid search
grid.fit(indep, dep)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
31 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
9 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1102: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.81687806 0.83230054 0.81367691 0.83370804
        nan        nan 0.81735797 0.83351752 0.81731292 0.83201305
        nan        nan 0.80854623 0.83479911 0.81809837 0.83504058
        nan        nan 0.81679883 0.83302583 0.81312459 0.83413729]
  warnings.warn(

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [11]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'log2', 'n_estimators': 100}:

In [12]:
table=pd.DataFrame.from_dict(re)

In [13]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002776,0.000891,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.002051,0.000661,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.041532,0.001879,0.004628,0.000682,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.844333,0.751316,0.831500,0.828998,0.828243,0.816878,0.033293,12
3,0.385004,0.007193,0.017558,0.002309,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.856282,0.773678,0.864750,0.827401,0.839393,0.832301,0.032059,7
4,0.041380,0.001864,0.005418,0.000665,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.841322,0.755508,0.852633,0.799195,0.819726,0.813677,0.034386,14
5,0.397434,0.017410,0.017129,0.001945,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.857740,0.779762,0.863306,0.829689,0.838043,0.833708,0.029661,4
6,0.002101,0.000711,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.002233,0.000451,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.133663,0.008465,0.004298,0.000557,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.827386,0.764151,0.848522,0.813801,0.832931,0.817358,0.028837,10
9,1.294987,0.051721,0.016924,0.001104,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.860041,0.778538,0.858645,0.826229,0.844134,0.833518,0.030078,5
10,0.132631,0.009110,0.004865,0.000713,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.839627,0.768553,0.835565,0.805541,0.837279,0.817313,0.027371,11
11,1.264409,0.019786,0.015143,0.000771,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.860145,0.780380,0.853292,0.824922,0.841326,0.832013,0.028451,8
12,0.001642,0.000911,0.000000,0.000000,friedman_mse,auto,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.001658,0.000091,0.000000,0.000000,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.042232,0.001714,0.005265,0.001757,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.829168,0.767957,0.827204,0.806208,0.812195,0.808546,0.022089,16
15,0.392437,0.014558,0.019731,0.001803,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.861226,0.780427,0.861735,0.829188,0.841420,0.834799,0.029851,2
16,0.043038,0.004165,0.004333,0.000498,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.839785,0.742684,0.850253,0.825627,0.832143,0.818098,0.038589,9
17,0.392164,0.016858,0.016102,0.001307,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.858448,0.780363,0.861898,0.831547,0.842947,0.835041,0.029440,1
18,0.001396,0.000698,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.001392,0.000696,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.059345,0.002701,0.004516,0.001288,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.838803,0.760297,0.836258,0.812672,0.835964,0.816799,0.029798,13
21,0.533916,0.012690,0.016194,0.001088,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.858701,0.773886,0.864347,0.826915,0.841280,0.833026,0.032383,6
22,0.056034,0.001614,0.004744,0.001086,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.846435,0.753500,0.851563,0.795439,0.818685,0.813125,0.036016,15
23,0.493101,0.024408,0.015096,0.002940,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.859632,0.777278,0.861750,0.831087,0.840939,0.834137,0.030663,3

In [14]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 25
BMI: 87
Children: 3
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [18]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[40301.7401377]

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(